[build]
  # Base directory for the build
  base = "."
  
  # Publish directory (where your frontend files are)
  publish = "votef"
  
  # No build command needed for static HTML files
  # command = ""

[build.environment]
  # Environment variables for the frontend
  NODE_ENV = "production"
  
  # Firebase Configuration (optional - will use defaults if not set)
  FIREBASE_API_KEY = "AIzaSyDh60ha_x6ZBFdicTb268kkIECHgAWwlME"
  FIREBASE_AUTH_DOMAIN = "voterc-c70d1.firebaseapp.com"
  FIREBASE_PROJECT_ID = "voterc-c70d1"
  FIREBASE_STORAGE_BUCKET = "voterc-c70d1.firebasestorage.app"
  FIREBASE_MESSAGING_SENDER_ID = "488886767779"
  FIREBASE_APP_ID = "1:488886767779:web:c7abc68d48eed56d776f16"
  FIREBASE_MEASUREMENT_ID = "G-1LVLBJ2JWM"
  
  # Feature Flags
  FIREBASE_ENABLED = "true"
  SMS_ENABLED = "true"
  ANALYTICS_ENABLED = "true"

# Redirect rules for SPA-like behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers for static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 